### ISSUE TITLE
Fail to start, and without any error output

### ISSUE THREAD

**Issue by zhangtiny123** [struCoder/pmgo#15]
Hi man ,
I've tried to use pmgo, it seems really cool, and friendly to me, as a pm2 user.
but I think there should be more examples .

I tried ```pmgo start /path/to/main.go app-name```
but failed , error output is 
```
FATA[0000] Failed to start go bin due to: ERROR: exit status 1 OUTPUT:

```
second line empty...
what's wrong with it please ?

**Comment by struCoder** [comment]
@zhangtiny123 

Hi zhangtiny123,
Thank you to report this issue.  it seems the error when go build your project, can you build success the following command?
```golang
go build -o out/path/projectName /path/to/main.go
```

**Comment by zhangtiny123** [comment]
Hi  @struCoder 
Thanks for your reply,
I'm sure that ```go build``` is OK, and any other suggestions ?

**Comment by struCoder** [comment]
@zhangtiny123 
I tried to reproduce your problem, but fail.
can you provide more details ?
some code that you write.

**Comment by zhangtiny123** [comment]
@struCoder 
Thanks for your trying to reproduce it. I found that it's my fault.
```pmgo start path/to/source/main.go app-name``` will fail to start and without any error message.
And I tried  ```pmgo start path/to/source/ app-name```, it works. 😃 😃

**Comment by royalecards** [comment]
Hello @struCoder , 

I also have the some problem when I run `pmgo start <start go file> <name>`

My project structure is something like this:

> home/ubuntu/go/src/github.com/my-auth

I already run go install and go build to build the binary file. And when I tried to run my application just with command `./main`, it has no problem at all.

So, in terminal I tried `pmgo start home/ubuntu/go/src/github.com/my-auth/ main`

But everytime it's always return 

> FATA[0000] Failed to start go bin due to: ERROR: exit status 1 OUTPUT:

Btw, I installed go 1.8 in ubuntu 14.04 and install pmgo using 
`$ go get github.com/struCoder/pmgo`
`$ mv $GOPATH/bin/pmgo /usr/local/bin`

So do you have any idea to solve my problem? 

Best regards,

**Comment by struCoder** [comment]
hi @royalecards 
when pmgo start your project, it just find your project source-directory and compile. so  you can try this
```go
pmgo start path/to/source-directory app-name
```

not pmgo start path/to/xx.go.

**Comment by royalecards** [comment]
Hi @struCoder,

As you can see from my last message, 

> So, in terminal I tried pmgo start home/ubuntu/go/src/github.com/my-auth/ main

I just specify the path to my project directory ` home/ubuntu/go/src/github.com/my-auth/` and then I use `main` as my process name. 
I'm not directly access my binary file or my go file (xx.go).

So, any idea?

Best regards,

**Comment by struCoder** [comment]
hi @royalecards 
sorry.
can you start your project by `go run command` ?
could you show me with your code? let me try to find the problem and solve it. 
if your project have some files you can zip it and send email to me.
i will keep it secret.
Thank you. :)

**Comment by nshah14285** [comment]
I am facing same error "FATA[0000] Failed to start go bin due to: ERROR: exit status 1 OUTPUT:"
It's a simple hello world example which prints hello, world.
I have followed the same steps like @royalecards mentioned.
Any idea how to solve?
