### ISSUE TITLE
对pmgo的建议

### ISSUE THREAD

**Issue by zxl777** [struCoder/pmgo#22]
我一直用pm2，其他功能够用，就是占内存，pm2+node要占用快100M了。

所以找到了pmgo。

pm2本身就可以根据Go源码变化自动编译运行go程序，用watch参数，调用一个.sh文件 
``` go run xxx.go ```
这样就可以了。

因此，pmgo只要能调用sh文件，并能监控文件变化就行了。
象这样 
``` pmgo start demo.sh --watch ```

pm2好就好在不仅管理node的程序，其他一切sh能启动的程序，都可以管理。
建议参考，相信用go可以写成万用的进程管理工具。

**Comment by struCoder** [comment]
@zxl777 
十分感谢您的提议，目前pmgo还是有很多的feature要做，我这边也收集了很多使用者的反馈，但是目前公司这边太忙啊，我会记下您的提议，挤挤时间准备上一个大版本。
