### ISSUE TITLE
License or any terms of use?

### ISSUE THREAD

**Issue by danielckv** [struCoder/pmgo#26]
You should put here your License for using this code for people who using it in their projects.

Please update.

**Comment by struCoder** [comment]
HI @danielckv 
MIT LICENSE FOR ALL CODE :)
https://github.com/struCoder/pmgo/blob/master/LICENSE

**Comment by danielckv** [comment]
thanks!

I'm working on `pmgo logs` command to get logs of all services. 
wait for a pr
