### ISSUE TITLE
Failed to reborn daemon due to daemon: Resource temporarily unavailable

### ISSUE THREAD

**Issue by jmesyan** [struCoder/pmgo#33]
why tip this, i can't run the pmgo, using centos7

**Comment by jmesyan** [comment]
the environment 
GOARCH="amd64"
GOBIN="/code/golang/bin"
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/code/golang"
GOPROXY=""
GORACE=""
GOROOT="/app/go"
GOTMPDIR=""
GOTOOLDIR="/app/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build246234099=/tmp/go-build -gno-record-gcc-switches"

just like the first time  ,I don't start any project,use pmgo list

**Comment by struCoder** [comment]
Hi @jmesyan 
I try to reproduce your problem, but everything was okay.
go version go1.11.2 linux/amd64
![image](https://user-images.githubusercontent.com/6498477/48469007-7c818900-e828-11e8-9274-acf5d038364e.png)

**Comment by boyunzheyue2** [comment]
@struCoder 
这个问题我这里可以稳定复现，go版本是1.12.7，复现步骤如下。
1、使用pmgo拉起一个进程，如：pmgo start /usr/bin/top top true。
2、kill -9 杀掉pmgo的进程。
3、pmgo list即可复现该问题。

**Comment by struCoder** [comment]
@boyunzheyue2 
感谢，我这边也跟进一下这个问题。
