### ISSUE TITLE
Add option for starting a built go binary

### ISSUE THREAD

**Issue by helloworldpark** [struCoder/pmgo#40]
Currently, ```pmgo start``` seems to build binaries from the beginning, but I think there should be some flexibility. How about adding a flag on ```pmgo start``` indicating that the process start from a binary built by a users' custom ```go build```?

**Comment by struCoder** [comment]
@helloworldpark 
Yeah. I agree with your suggestion.
New version coming soon.

**Comment by struCoder** [comment]
@helloworldpark 
Just checkout beta and rebuild
https://github.com/struCoder/pmgo#beta-featuresgit-checkout-beta-and-rebuild

**Comment by helloworldpark** [comment]
Sorry for late reply. I just tested the beta feature, and it works well!
