### ISSUE TITLE
FATA[0000] Failed to start go bin due to: ERROR: exit status 1 OUTPUT: 

### ISSUE THREAD

**Issue by areliszxz** [struCoder/pmgo#41]
try to execute the command
pmgo start /home/test/go/src/test test
and send the error
FATA [0000] Failed to start go to due: ERROR: exit status 1 OUTPUT:
there is some parameter -v or how can I see the debug to see why it sends the erorr

**Comment by struCoder** [comment]
@areliszxz 
You can run `tail -f ~/.pmgo/main.log` to see what happens

**Comment by jmesyan** [comment]
can't support the go module way @struCoder

**Comment by wpbawsed** [comment]
@struCoder 您好～我也遇到相同問題，我將檔案放在$GOPATH/src/test 中執行檔為main，使用pmgo start /User/{{user_name}}/go/src/test main時發生FATA [0000] Failed to start go to due: ERROR: exit status 1 OUTPUT:，想請問一下設定哪邊有問題嗎？

**Comment by struCoder** [comment]
@wpbawsed 
您好，你可以看一下文檔，比如你有一個test目錄在$GOPATH/src中，那麼啟動方式為:
pmgo start test/ app_name

如果你的項目已經編譯了可以看這裡的說明:[Bete Features](https://github.com/struCoder/pmgo#beta-featuresgit-checkout-beta-and-rebuild)

**Comment by wpbawsed** [comment]
@struCoder 您好
想問一下pmgo start 執行的app_name是$GOPATH/src/test底下的main.go嗎？還是go build完之後的檔案？

另外，剛剛使用pmgo start /Users/{{user_name}}/go/src/{{project_name}}/bin mac_darwin true --args="arg1 arg2 arg3"還是發生FATA [0000] Failed to start go to due: ERROR: exit status 1 OUTPUT:。

專案的main.go在/Users/{{user_name}}/go/src/{{project_name}}/下，執行檔在/Users/{{user_name}}/go/src/{{project_name}}/bin下，名稱為mac_darwin。
