### ISSUE TITLE
請問 如果我的app 返回的statusCode不是 0的話，也算成功執行嗎

### ISSUE THREAD

**Issue by aloha1003** [struCoder/pmgo#43]
你好，我用pmgo 執行 我的範例
`package main

import (
	"fmt"
	"log"
	"os"
	"os/exec"
)

func main() {
	cmd := exec.Command("/bin/sh", "./test.sh", "xx")
	out, err := cmd.CombinedOutput()
	if err != nil {
		log.Fatalf("cmd.Run() failed with %s\n", err)
	}
	fmt.Printf("combined out:\n%s\n", string(out))
	os.Exit(1)
}
`

返回的狀態不是0的值，這樣pmgo也會視為執行正常嗎

**Comment by struCoder** [comment]
@aloha1003 
你好，pmgo的初衷是為了類似運行http server這樣需要長久守護的進程，並不是如你所展示的demo 的code。
祝好:)
