### ISSUE TITLE
Support for Go Module 

### ISSUE THREAD

**Issue by helloworldpark** [struCoder/pmgo#46]
Now that go module has been released, supporting for go module would be pleasant.
One problem is that, [logrus](https://github.com/sirupsen/logrus), the logging library makes people very hard because of [this issue](https://stackoverflow.com/questions/55537287/unexpected-module-path-github-com-sirupsen-logrus). Is there any plan for supporting go module?

**Comment by struCoder** [comment]
hi @helloworldpark 
In beta Branch supported go module.

**Comment by struCoder** [comment]
Replace logrus package, and which one you think is best.
And you can make contributions to this project. Welcome 👍
