### ISSUE TITLE
[Beta] Is it necessary to copy compiled binary for starting it?

### ISSUE THREAD

**Issue by helloworldpark** [struCoder/pmgo#47]
https://github.com/struCoder/pmgo/blob/173a49eab8b992cc0786da35675fdba8bb253fe5/lib/preparable/process.go#L51

Seems like it is necessary to copy a pre-compiled binary to start. Is it necessary? Think this could be skipped, but don't know if there could be any side effects.

**Comment by struCoder** [comment]
Fixed By @helloworldpark [PR](https://github.com/struCoder/pmgo/pull/54)
