### ISSUE TITLE
Cannot get the project with go get command successfully due to some of required go package repository path changed.

### ISSUE THREAD

**Issue by kanatat-asp** [struCoder/pmgo#60]
The project repository cannot be download successfully when using go get command.

`go get github.com/struCoder/pmgo`

After using command I got an output as below.
`go get: github.com/Sirupsen/logrus@none updating to
               github.com/Sirupsen/logrus@v1.8.1: parsing go.mod:
               module declares its path as: github.com/sirupsen/logrus`

This might occurred due to required package's repository path has changed from github.com/sirupsen/logrus to github.com/Sirupsen/logrus.

Ref. Image
![Screen Shot 2564-03-23 at 17 13 28](https://user-images.githubusercontent.com/20646649/112130458-17f64600-8bfb-11eb-8361-97a1bb8bd64b.png)

Please kindly considered a go mod packages update.
Thank you, in advance.

**Comment by struCoder** [comment]
Hi @kanatat-asp 
Thanks.
go.mod deps has be updated.
